### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/node-build#127]
While preparing another merge from ruby-build, I noticed they have adopted the Contributor Covenant as their Code of Conduct. rbenv/ruby-build@b96c23183b67fd1105d6559da3a17043302340e9

http://contributor-covenant.org/version/1/4

Shall we adopt similarly? I agree with the general principle of Codes of Conduct, and defer to others who have spent more time thinking and discussing this topic as to the appropriate contents of the CoC. So I am in favor of supporting the contributor covenant.

/@OiNutter @jawshooah

**Comment by OiNutter** [comment]
Absolutely! Personally I feel it's ridiculous that this even needs to be a thing, manners cost nothing, but sadly it does and at least if we are clear on our stance then we can feel perfectly justified in directing people towards the virtual door when they are disrespectful.

**Comment by jawshooah** [comment]
Totally on board with this.

**Comment by jasonkarns** [comment]
Opened #129 -  merges updates from ruby build including code of conduct.

It's a verbatim copy of ruby-build's code of conduct, with only the maintainers list updated. good to go?

**Comment by jasonkarns** [comment]
closed by #138
