### ISSUE TITLE
Need FAQ or Troubleshooting tips on wiki or in repo

### ISSUE THREAD

**Issue by jasonkarns** [nodenv/node-build#160]
Our readme instructs people to read the wiki https://github.com/nodenv/node-build#getting-help but the wiki is empty.

We need some common FAQs or troubleshooting tips documented somewhere.

**Comment by joshmorel** [comment]
I'm going to spend some more time with the tool, then I will try this. Maybe within a month?

**Comment by mistydemeo** [comment]
I noticed that the wiki is still empty. Maybe it's worth removing that link from the README until there's content for users to read.

**Comment by jasonkarns** [comment]
wiki added: https://github.com/nodenv/node-build/wiki

Leaving this open as still would like some docs on:
- [ ] handling of precompiled binaries
- [ ] usage of EOL/LTS-maint warnings
