### ISSUE TITLE
New checksums released today?

### ISSUE THREAD

**Issue by rustygeldmacher** [nodenv/node-build#223]
Hi there,

As part of our CI process we use node-build to install whatever node is listed in a repo's `.node-version` file. Today our builds started failing because the checksum for node v6.9.2 was not matching.

I see that in the latest node-build, the expected checksum for [linux-x64](https://github.com/nodenv/node-build/blob/master/share/node-build/6.9.2#L9) is `cbf6a35b035c56f991c2e6a4aedbcd9f09555234ac0dd5b2c15128e2b5f4eb50`, but the official nodejs checksum is `c8acada3301857ddb650bc9d4383eaba4b90ebd4d89740729297bffb630a3531` (from https://nodejs.org/dist/v6.9.2/SHASUMS256.txt.asc).

If you `gpg --verify` that checksum file, you'll see that the signature was created today, suggesting to me that the checksums were changed today.

I'd love to contribute by updating the checksums in node-build to match the latest ones published from the node team -- is there any kind of automation around this process that you guys have built?

Thanks a lot, we really love nodenv and all its plugins!

**Comment by jasonkarns** [comment]
fixed by #224 and #225.  see also https://github.com/nodejs/node/issues/10630

Updated build definitions now in master and release as https://github.com/nodenv/node-build/releases/tag/v2.5.2

Update to homebrew coming soon.

**Comment by jasonkarns** [comment]
https://github.com/Homebrew/homebrew-core/pull/8530
