### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by ihackalot** [nodenv/node-build#293]
On `brew upgrade node-build` from node-build v2.6.7 brew returns the following error:
```
Error: SHA256 mismatch
Expected: c98f7de6a749520fb7155c1b315f01804eb6554f8edb0d45bd7514f9e9a1dc44
Actual: 6c636ae7bcead1186ee392cd9974e764cb0ba82165396366d502987f0d3c466f
```

**Comment by ihackalot** [comment]
I close the issue as a couple hours later it's no more.
Thanks!

**Comment by jasonkarns** [comment]
Yep, fixed here. https://github.com/Homebrew/homebrew-core/pull/16020#issuecomment-317768450

Sorry, there were a flood of github notifications coming in around this and I lost track which had been replied to.

**Comment by ihackalot** [comment]
You sorry? You gotta be kidding me man 😄 
Just thanks. Really appreciate your work here!
