### ISSUE TITLE
NODE_BUILD_MIRROR_URL not working?

### ISSUE THREAD

**Issue by mytunguyen** [nodenv/node-build#297]
Hi there. I installed `nodenv 1.1.1` and then installed node-build
```
git clone https://github.com/nodenv/node-build.git
cd node-build
./install.sh
```
But when I try using a mirror, it still reaches out to https://nodejs.org
```
~ # export NODE_BUILD_MIRROR_URL=http://internal-artifactory.com:8081/artifactory/nodejs/dist/
~ # nodenv install 4.2.1
sha256sum: unrecognized option: quiet
BusyBox v1.24.2 (2017-01-18 14:13:46 GMT) multi-call binary.

Usage: sha256sum [-c[sw]] [FILE]...

Print or check SHA256 checksums

	-c	Check sums against list in FILEs
	-s	Don't output anything, status code shows success
	-w	Warn about improperly formatted checksum lines
Downloading node-v4.2.1-linux-x64.tar.gz...
-> https://nodejs.org/dist/v4.2.1/node-v4.2.1-linux-x64.tar.gz
error: failed to download node-v4.2.1-linux-x64.tar.gz
```
Did I miss a step? Thanks!

**Comment by misheska** [comment]
I hit this one myself - you need to make sure that the `shasum` command is present, otherwise it will ignore `NODE_BUILD_MIRROR_URL`:
https://github.com/nodenv/node-build/blob/master/bin/node-build#L917-L920

If you're using RHEL: `yum install perl-Digest-SHA -y`

**Comment by jasonkarns** [comment]
@mytunguyen would you mind providing some more details on your OS version and version of sha256sum?

**Comment by jasonkarns** [comment]
thanks @misheska !

**Comment by jasonkarns** [comment]
Closing from inactivity and assuming the issue is due to weird version of shasum.

Feel free to re-open with more details (OS version and version of sha256sum) and we can see about improving the checksum code to handle a version without the `--quiet` flag.
