### ISSUE TITLE
Definition for graalvm node?

### ISSUE THREAD

**Issue by mutech** [nodenv/node-build#405]
Hi! Are you considering to support Graalvm's node implementation?

**Comment by jasonkarns** [comment]
Yes! Would love PRs to add support for other node engines.

If you decide to tackle this, I'll point out the jxcore definitions (and to a lesser extent, iojs) as examples for how to proceed.

**Comment by mutech** [comment]
Will look into it when I find some time.

**Comment by jasonkarns** [comment]
@mutech There aren't really any strict requirements. The idea is that most "nodes" would be pseudo interchangeable, so yes, it would be expected that the final installation directory have a bin/node and bin/npm. However, it's not required that they be there in the downloaded package. node-build can do renames and directory tweaks after compilation or downloading.

It might be worthwhile to reference ruby-build's definitions for jruby considering the use of the jvm:

Example: https://github.com/rbenv/ruby-build/blob/master/share/ruby-build/jruby-9.2.5.0

```
require_java7
install_package "jruby-9.2.5.0" "https://s3.amazonaws.com/jruby.org/downloads/9.2.5.0/jruby-bin-9.2.5.0.tar.gz#f4ad088082eca73561df983f6cb0a937b966cba3a36454e88f63930ed2bdf349" jruby
```

The require_java7 function:
https://github.com/rbenv/ruby-build/blob/095d9db34fcbe24d38a16c9462cb853748bc65e7/bin/ruby-build#L807-L814 (does graalvm have similar jdk version requirements?)

The install_package line is a standard tarball download + extract. Then the "jruby" flag at the end of that line triggers the `build_package_jruby` function, which does all the stuff necessary for extracting the tarball into the right format, with the right executable files, and with the necessary symlinks

https://github.com/rbenv/ruby-build/blob/095d9db34fcbe24d38a16c9462cb853748bc65e7/bin/ruby-build#L725-L733

**Comment by jasonkarns** [comment]
I spiked together the following definition:

```
graal_platform() {
  case "$(uname -s)" in
  "Darwin") echo "macos";;
  "Linux") echo "linux";;
  *)
    echo "no builds available" >&2
    exit 1;;
  esac
}

build_package_graal() {
  build_package_copy
  cd "$PREFIX_PATH"
  mv -f Contents/Home/* .
  rm -rf Contents
}

install_package "graalvm+ce-1.0.0-rc10" "https://github.com/oracle/graal/releases/download/vm-1.0.0-rc10/graalvm-ce-1.0.0-rc10-$(graal_platform)-amd64.tar.gz" graal
```

and installed via: `nodenv install -f share/node-build/graalvm+ce-1.0.0-rc10`

which worked: 
```
$ nodenv shell graalvm+ce-1.0.0-rc10 
$ npm version
{ '@nodenv/node-build': '4.3.0',
  npm: '6.2.0',
  ares: '1.14.0',
  http_parser: '2.8.0',
  modules: '64',
  napi: '3',
  nghttp2: '1.32.0',
  node: '10.9.0',
  openssl: '1.1.0i',
  uv: '1.22.0',
  v8: '6.7.0.0-node.0',
  zlib: '1.2.11' }
```

However, there are a whole bunch of bins in there that we should probably remove. I don't think a user would be happy that `java` or `javac` is now shimmed by nodenv.

Any idea which of these are critical? Should we just keep node, npm and js* ?

**Comment by jasonkarns** [comment]
Still need to 
- [ ] add source builds (right now, it only installs the binaries)
- [ ] remove as many things from bin/ as possible (this reduces the amount of shims created within nodenv)
