### ISSUE TITLE
11.10.0 missing

### ISSUE THREAD

**Issue by pvinis** [nodenv/node-build#468]
The newest node version is missing. How can we add it?

**Comment by jasonkarns** [comment]
was added over a week ago: https://github.com/nodenv/node-build/blob/master/share/node-build/11.10.0

https://github.com/nodenv/node-build/commit/c8d9266e00ed0e457d35d159f2fba065d0ddf308

**Comment by jasonkarns** [comment]
To clarify, the definition was in master but there hadn't been a version bump of node-build since then. see https://github.com/nodenv/nodenv/wiki/FAQ#available-node-versions-are-out-of-date for ways to stay up to date without waiting on the node-build version lag.

**Comment by pvinis** [comment]
Thank you for clearing that up. I did try `node-build-update-defs` but it was failing. I will try the `update` plugin.

**Comment by jasonkarns** [comment]
If you're able, feel free to open issues over at https://github.com/nodenv/node-build-update-defs/issues regarding the update-defs plugin...

(also note, the nodenv-update plugin updates all plugins that are installed via git. if you installed nodenv and/or node-build via homebrew, it can't update those)
