### ISSUE TITLE
Support for v12.8.0

### ISSUE THREAD

**Issue by conn** [nodenv/node-build#511]
`v12.8.0` is the latest current version of NodeJS:
https://nodejs.org/download/release/latest-v12.x/

It came out only a few days ago so it's not surprising that it hasn't been added. Please update at your convenience. 🙂

**Comment by jasonkarns** [comment]
Your version of node-build must be out of date.

the version def for 12.8.0 was added 6 days ago: https://github.com/nodenv/node-build/commit/ba65ff155259c6461956fd8639b9fee9c24d93da#diff-7e154c5162b8928edc4da3f323e81873 so it was installable if your node-build installation is via git, by pulling latest master.

node-build [4.6.3](https://github.com/nodenv/node-build/releases/tag/v4.6.3) was released 3 days ago 12.8.0, so if your node-build installation is via npm, you just needed up `npm i -g @nodenv/node-build@latest` and 12.8.0 would be installable.

And the latest node-build was updated in homebrew [3 days ago](https://github.com/Homebrew/homebrew-core/pull/42989) as well, so a brew-update and brew upgrade node-build (or brew upgrade nodenv) would make 12.8.0 available to you.

Also, if you want the latest releases of node without waiting on node-build to update, you can install the [node-build-update-defs](https://github.com/nodenv/node-build-update-defs) plugin which will scrape nodejs.org and generate the build definitions for you. (The same tool we use internally to generate the build defs for node-build.)
