### ISSUE TITLE
Security Releases(npm to v6.13.4)

### ISSUE THREAD

**Issue by toshi-toma** [nodenv/node-build#550]
The master branch has the latest nodes merged including `npm v6.13.4`.
I confirmed the latest node-build version source code(tar.gz). Looks like it hasn't been released yet.
https://github.com/nodenv/node-build/releases/tag/v4.6.8

required commits
- https://github.com/nodenv/node-build/commit/b82c0a0932f4b5dc2976a8b2032e35b925cee68f
- https://github.com/nodenv/node-build/commit/00af96cc4053f5501d1c2276d7c0fea15affd38e
- https://github.com/nodenv/node-build/commit/733ac11e174ef0726f2cad97dbc373e2d819f449
- https://github.com/nodenv/node-build/commit/a6f9b98e37a0a13975b88cab383f263c44c31b59

Nodejs Security Releases
ref: https://nodejs.org/en/blog/vulnerability/december-2019-security-releases/

**Comment by jasonkarns** [comment]
[4.6.9](https://github.com/nodenv/node-build/releases/tag/v4.6.9) has been released which includes these patched nodes.

[4.7.0](https://github.com/nodenv/node-build/releases/tag/v4.7.0) has also been released which updates node 8 to EOL
