### ISSUE TITLE
homebrew's node-build appears to be out of date

### ISSUE THREAD

**Issue by erikphansen** [nodenv/node-build#551]
Perhaps this is user error on my part, but it appears that the version of node-build that homebrew installs is out of date.

I have the latest versions of both nodenv and node-build installed via homebrew. Running `nodenv install -l` shows that v13.2.0 is the latest version of node that's available while this repo shows that 13.5.0 was added on Dec 18. Is it possible that the past few releases of node-build somehow did not propagated to homebrew?

**Comment by jasonkarns** [comment]
We haven't had any release of node-build for a while. The latest on github is just `master` (unreleased). We don't release new versions of node-build with _every_ release of node as that's a pretty frequent occurrence. Users that need to keep up with the very latest node releases may install node-build via git-clone (and hence would have latest node definitions from `master`), or may install the node scraper as documented in the readme: https://github.com/nodenv/node-build#updating-available-build-versions

**Comment by jasonkarns** [comment]
Started a release this morning, but we're having an issue with the LTS/EOL validations... Hopefully we can get that ironed out and drop a homebrew release soon.

**Comment by erikphansen** [comment]
Thanks for the quick response, @jasonkarns.
