### ISSUE TITLE
Why am I unable to use the latest node LTS using node build on MacOS?

### ISSUE THREAD

**Issue by mileslane** [nodenv/node-build#567]
I use `brew update && brew upgrade node-build` but node 12.16.0 is not available.
It looks like it ought to be supported:
https://github.com/nodenv/node-build/blob/master/share/node-build/12.16.0

As you can see from this snippet, the most recent LTS versions of node don't show up with `node-build --definitions`:
```
...
12.14.0
12.14.1
13.0.0
...
```
I seem to have the latest release of node-build:
`node-build --version`
node-build 4.7.1

Also, I tried:
`nodenv update-version-defs` and got this:
```
Checking for new nodejs versions
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1475:34)
    at TLSSocket.emit (events.js:321:20)
    at TLSSocket._finishInit (_tls_wrap.js:918:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:688:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
```
I used `NODE_TLS_REJECT_UNAUTHORIZED='0' nodenv update-version-defs` to update my local list.  It SEEMED to have worked:
```
12.16.0 written
12.15.0 written
13.7.0 written
13.8.0 written
10.19.0 written
```
But then those additions do not show up when I run `nodenv install --list`.
Help?

**Comment by jasonkarns** [comment]
What's in node-build master may or may not be released in a version of node-build.

https://github.com/nodenv/node-build/compare/v4.7.1...master

And further still, what's released in a version of node-build may or may not be the latest version available via homebrew.

The TLS issue looks like a real concern, though. Would you mind opening that on the plugin's repo? https://github.com/nodenv/node-build-update-defs/issues/new

**Comment by jasonkarns** [comment]
To the last question: 

> But then those additions do not show up when I run `nodenv install --list`.

That _may_ be a bug.

per the [usage section](https://github.com/nodenv/node-build-update-defs#usage) for that plugin:

> By default, this will create build definitions in the plugin's share/node-build/ directory. This directory can be overridden with --destination. For scraped definitions to be picked up by node-build/nodenv install, the destination directory must be present in NODE_BUILD_DEFINTIONS. See special environment variables

nodenv ought to include all plugins' `share/node-build/` directory in the definition lookup by default. So if that's not working, I'd like to dig into that in an issue on the plugin's repo as well. In particular, I'm curious how you have the plugin installed: via git clone, homebrew or npm?

**Comment by jasonkarns** [comment]
tagged latest master: https://github.com/nodenv/node-build/releases/tag/v4.7.2

**Comment by jcrben** [comment]
For other nodenv users who encounter this on Google, the reason I was getting the TLS plaintext warning is that I'd at some point set `registry=http://registry.npmjs.org/` in my npmrc
