### ISSUE TITLE
Release on homebrew

### ISSUE THREAD

**Issue by arcanis** [nodenv/node-build#618]
The latest Node releases are fixing [CVEs marked as high impact](https://nodejs.org/en/blog/release/v10.21.0/), it would be important to make them widely available as soon as possible.

As a side note, wouldn't it make sense to include the `update-version-defs` command by default? This way users wouldn't be blocked on this package to start using new releases (ideally I'd even prefer the command to be optional, since it still requires I tell my engineers to run a command on their fleet).

**Comment by jasonkarns** [comment]
Just kicked off the release flow: https://github.com/nodenv/node-build/actions/runs/124041472



> As a side note, wouldn't it make sense to include the `update-version-defs` command by default?

Possibly. The rationale for why node-build uses static build definitions is historical and inherited from ruby-build. Some of those historical reasons are still compelling today for node, others are not. I want to noodle it around a bit, but it's a possibility. (Though, if it did happen, we'd likely forgo the `update-version-defs` plugin entirely, and just have node-build auto-install the nodes without needing the static build definition. Perhaps a node-install plugin that could take the place of node-build entirely and eventually be the default? 🤷 )
