### ISSUE TITLE
What is the process to get the latest definitions published?

### ISSUE THREAD

**Issue by cy6erskunk** [nodenv/node-build#621]
What is the correct way of getting latest definitions published? I could not find description of this process anywhere,
it is simply doing a new release of `node-build`?

I was trying to use node version `12.18.1` which was released a week ago, but had to update definitoins locally using `update-version-defs` to get node version `12.18.1`, but it's not very scalable to make everyone in the team to use it.

**Comment by jasonkarns** [comment]
Just now documented!

https://github.com/nodenv/node-build/wiki/Updating-Available-Definitions#the-process-for-releasing-official-definitions
