### ISSUE TITLE
Cannot install Node.js v14.15.5

### ISSUE THREAD

**Issue by y-shoji-mfw** [nodenv/node-build#667]
Hello. When I execute `nodenv install 14.15.5` , I got the following message.

```bash
node-build: definition not found: 14.15.5

See all available versions with `nodenv install --list'.

If the version you need is missing, try upgrading node-build:

  git -C /Users/shoji.yu/.nodenv/plugins/node-build pull
```

I try `git -C /Users/shoji.yu/.nodenv/plugins/node-build pull` , but there is no changes.

```bash
$ git -C /Users/shoji.yu/.nodenv/plugins/node-build pull
Already up to date.
```

I suspect that this PR ( https://github.com/nodenv/node-build/pull/666 ) failing is related with this.  
Could anyone help this problem?

**Comment by Sixeight** [comment]
I try to run same actions at my forked repository, then all checks were passed!
https://github.com/Sixeight/node-build/pull/1

Could anyone rerun actions and merge the PR?

**Comment by GSokol** [comment]
@jasonkarns, @ericanderson, @charlesbjohnson, please! :pray:

**Comment by jasonkarns** [comment]
https://github.com/nodenv/node-build/commit/2461b8fb56b3b405c26a4047b4d314d139b5d945
