### ISSUE TITLE
`incorrect data check` error - How to pass additional arguments when building node?

### ISSUE THREAD

**Issue by convenient** [nodenv/node-build#719]
I am having an issue on the m1 silicon macbooks whereby the node version is installed, but subsequent `npm install` fails with `incorrect data check` error.

See main issue here https://github.com/nodejs/node/issues/39313

Looking at https://github.com/vercel/pkg-fetch/commit/925111ba5ebf8a7d7ffdf6e45cffb202103968f7 we can build node with a `--shared-zlib` flag which seems to fix the issue?

I can see that this is possible within `nvm`, https://github.com/nvm-sh/nvm/pull/2653#issuecomment-982219834

Is it possible to do something similar when building node with this tool?

**Comment by convenient** [comment]
I think this is correct, sorry got a bit overwhelmed by documentation there.

```
NODE_CONFIGURE_OPTS="--shared-zlib" arch -x86_64 nodenv install $VERSION
```

**Comment by jasonkarns** [comment]
Yes, that's correct. `NODE_CONFIGURE_OPTS` (and `NODE_CONFIGURE_OPTS_ARRAY`) are passed to `./configure` before invoking `make`. (for which there is also then `NODE_MAKE_OPTS` and `NODE_MAKE_OPTS_ARRAY`)

Did you get it sorted?

**Comment by convenient** [comment]
yes i did get it sorted thanks @jasonkarns
