### ISSUE TITLE
Node.js 17.4.0 release

### ISSUE THREAD

**Issue by ai** [nodenv/node-build#726]
[Node.js 17.4.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V17.md#17.4.0) was released, but we still has no `node-build` update.

```sh
$ asdf install nodejs 17.4.0
node-build: definition not found: 17.4.0
```

**Comment by ai** [comment]
Fixed in https://github.com/nodenv/node-build/pull/725

**Comment by cj81499** [comment]
Seems to be failing for 17.7.1

```sh
> asdf install nodejs latest
Trying to update node-build... ok
node-build: definition not found: 17.7.1
```
