### ISSUE TITLE
GitHub Actions workflows are broken

### ISSUE THREAD

**Issue by minimum2scp** [nodenv/node-build#813]
Some workflows are broken.

![image](https://github.com/nodenv/node-build/assets/162862/38b4e88f-8f0a-48ee-8073-7ac585fe5a53)

@jasonkarns 
Can you take a look at these workflows?

**Comment by jasonkarns** [comment]
Yeah, thanks for the ping

**Comment by jasonkarns** [comment]
(Will be ~1 week)

**Comment by rmehner** [comment]
@jasonkarns is there anything we can help with? No pressure, just genuine offer to help. Things take time and you're a human first :)

**Comment by matzkoh** [comment]
I found a report that it was just a token issue.
Just regenerating and updating secrets might solve the problem.
https://github.com/peter-evans/create-pull-request/issues/2094

**Comment by jasonkarns** [comment]
token updated, thanks for your patience https://github.com/nodenv/node-build/actions/runs/5501964225
