### ISSUE TITLE
Could you release a new version? (v4.9.117)

### ISSUE THREAD

**Issue by Sixeight** [nodenv/node-build#818]
I am looking forward new version of node-build to update using HomeBrew.
Could you release a new version?

current: [v4.9.116](https://github.com/nodenv/node-build/releases/tag/v4.9.116)

**Comment by aphedges** [comment]
See #813 for the existing discussion on this. In short, something broke and the maintainer hasn't had time to fix it.

**Comment by jasonkarns** [comment]
done, and thank you for the patience: https://github.com/nodenv/node-build/releases/tag/v4.9.117
