### ISSUE TITLE
NodeJS 21

### ISSUE THREAD

**Issue by noraj** [nodenv/node-build#835]
NodeJS 21 is out https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V21.md#21.0.0

**Comment by noraj** [comment]
Have you a script to automatically get the links and generate the hashes for those files: https://github.com/nodenv/node-build/blob/master/share/node-build/20.8.1?

**Comment by jasonkarns** [comment]
covered by https://github.com/nodenv/node-build/pull/833
