### ISSUE TITLE
CI: version and generate definition failing

### ISSUE THREAD

**Issue by noraj** [nodenv/node-build#852]
It has been 3 weeks that the CI is failing. https://github.com/nodenv/node-build/actions

So node-bot is no longer submitting PR for newer versions.

So we are missing 2.9.0+ -> 2.11.1 and 2.6.2+ -> 2.7.1.

**Comment by jasonkarns** [comment]
I'll get into it this weekend.

**Comment by LaughDonor** [comment]
Any updates @jasonkarns ?

**Comment by jasonkarns** [comment]
Token bumped. Sorry for the delay folks.
