### ISSUE TITLE
Listing locally installed versions as documented with `nodenv build -L` does not work

### ISSUE THREAD

**Issue by martinblostein** [nodenv/node-build#854]
Following the instructions [here](https://github.com/nodenv/nodenv?tab=readme-ov-file#installing-node-versions):

    # list latest stable versions:
    $ nodenv install -l
    
    # list all local versions:
    $ nodenv install -L
    
    # install a Node version:
    $ nodenv install 16.13.2
    
 The first and last commands work as described, but the middle one does not seem to be recognized. `nodenv versions` seems to be the correct command for this, but I am not sure if that should be substituted in or if `nodenv install` is supposed to have such a command.

**Comment by jasonkarns** [comment]
This will be resolved soon with #876. If you're able to give that branch a try before I land it next week, I'd love to hear any feedback.

**Comment by jasonkarns** [comment]
This has now been released. https://github.com/nodenv/node-build/releases/tag/v5.0.0

Happy to hear feedback and if it fixes the issue for you.
