### ISSUE TITLE
Nodenv not compatible with windows 11?

### ISSUE THREAD

**Issue by sanketb9175** [nodenv/node-build#865]
Hi there! I'm new to `nodenv` and trying to run it on windows 11. However, I'm facing below error and it seems `nodenv` is not compatible with windows 11. Is there a fix for this? Am I missing anything?
```npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for nodenv@0.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32
```

**Comment by sanketb9175** [comment]
Its me again! After some research and going through the documentation, running below helped. Felt like a beginners mistake! :) 
`npm install node-env-run --save-dev`

**Comment by jasonkarns** [comment]
`node-env-run` is not affiliated with or related to nodenv in any way.

but no, nodenv is not officially supported on windows. nodenv (like its upstream parent `rbenv`) is built on POSIX and requires compliant bash.
